import { createFlagsmithInstance } from "flagsmith/isomorphic";
import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "./Providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const flagsmith = createFlagsmithInstance();
  await flagsmith.init({
    environmentID: process.env.NEXT_PUBLIC_FLAGSMITH_ID,
  });
  await flagsmith.identify(123, { email: "eddie@eddiehub.org" });
  const serverState = flagsmith.getState();
  console.log(serverState);
  return (
    <html lang="en">
      <Providers serverState={serverState}>
        <body className={inter.className}>{children}</body>
      </Providers>
    </html>
  );
}
