import { createFlagsmithInstance } from "flagsmith/isomorphic";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const flagsmith = createFlagsmithInstance();
  await flagsmith.init({
    environmentID: process.env.NEXT_PUBLIC_FLAGSMITH_ID,
  });
  const serverState = flagsmith.getState();
  console.log(serverState);
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
